### ISSUE TITLE
How to integrate this with a simple transformer ?

### ISSUE THREAD

**Issue by mistycube** [lucidrains/HTM-pytorch#1]
The code seems to only compute memory attention. How can I have an encoder or decoder self attention with HTM Attention afterwards ?

**Comment by lucidrains** [comment]
@mistycube yea, you'll have to do some work to integrate this into a transformer-xl system, and make sure to use the auxiliary reconstruction loss as mentioned in the paper

you can use https://github.com/lucidrains/compressive-transformer-pytorch as a guide

**Comment by lucidrains** [comment]
@mistycube i think this repository will only focus on the hierarchical attention scheme, as i see it being more generally applicable
